config/routes.rb
Sample::Application.routes.draw do
  root :to => "pages#help"
  get "pages/help"
  get "pages/home"
  get "pages/develper"

  

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def help
  end

  def home
  end

  def develper
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body data-no-turbolink = "true">
	<div class="navbar">
              <div class="navbar-inner">
                <div class="container">
                  <ul class="nav">
                    <li> <%=link_to "help" , pages_help_path %> </li>
                    <li> <%=link_to "Home" , pages_home_path %> </li>
                    <li> <%=link_to "developer" , pages_develper_path %> </li>
                  </ul>
                </div>
              </div>
            </div>
            

<%= yield %>

</body>
</html>

app/views/pages/develper.html.erb
<div class="hero-unit">
                <h1>Developer</h1>
 
    <p>i m new developer, give feedbacks</p>
 
    <a href="#" class="btn btn-large btn-danger"> development</a>
    <%= image_tag("monkey.jpg" ,:height=>"100",:width=>"100") %> 
 </div>

app/views/pages/help.html.erb

	
	
<div class="hero-unit">
                <h1>Help us</h1>
 
    <p>i am new in this field plz give ur suggestions and improve my knowledge</p>
 
    <div>
    	<%= link_to "donate" , '#' , :class => "btn btn-primary" , :id => "riddhi" %> 
    
    		<p class = "xyz">thoduk je samji ne aapo e....</p>
    </div>
 </div>

app/views/pages/home.html.erb
<div class="hero-unit">
                <h1>Welcome home</h1>
 
    <p>this is a home page</p>
 
   <%=link_to "wassup", "#" , :class => "btn btn-danger" , :id => "done" %>
  
 </div>
  <div class = "well">
    <div id="123" style="background:pink;height:200px;width:500px;position:absolute">
    	Home
    </div>
   </div>